"""
Public API for hapy.meta.

This module provides stable entrypoints for the meta-analysis of results generated by hapy, which includes the three data types, AA, HLA and SNP.
"""
from __future__ import annotations
import time

from ..stats.progress import format_seconds

from .io import read_input_files
from .combine import inv_var_meta_studies, stouffers_meta_studies


def meta_analyse(fileloc, data_type,  beta='Uni_Coef', se="Uni_StdErr", pval="LR_p", variant_col="VARIANT", prefix="META", interaction=False):
    t0 = time.perf_counter()

    if interaction:
        inv_var, stouffers = read_input_files(fileloc, data_type, interaction=True)

        FE_meta, Stouffers_meta = None, None
        if data_type=="AA":
            print("Performing Stouffer's Method Meta-analysis")
            Stouffers_meta = stouffers_meta_studies(stouffers, pval=pval, variant_col="INTERACTION", prefix=prefix)
        else:
            print("Performing Inverse-Variance Meta-analysis")
            FE_meta = inv_var_meta_studies(inv_var, beta="I_coef", se="I_StdErr", variant_col="INTERACTION", prefix=prefix)

    else:
        inv_var, stouffers = read_input_files(fileloc, data_type)

        FE_meta, Stouffers_meta = None, None
        if inv_var:
            print("Performing Inverse-Variance Meta-analysis")
            FE_meta = inv_var_meta_studies(inv_var, beta=beta, se=se, variant_col=variant_col, prefix=prefix)
        if stouffers:
            print("Performing Stouffer's Method Meta-analysis")
            Stouffers_meta = stouffers_meta_studies(stouffers, pval=pval, variant_col=variant_col, prefix=prefix)

    print(f"Meta-analysis completed in {format_seconds(time.perf_counter() - t0)}", flush=True)
    return FE_meta, Stouffers_meta